Traceback (most recent call last):
  File "/home/jennywu/.local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/jennywu/.local/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/jennywu/.local/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/jennywu/.local/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/jennywu/.local/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/jennywu/.local/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/jennywu/.local/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#SELECT Titel, Laenge * 0.016667 AS Stunden, â€˜std.â€˜ AS inStunden FROM Film

__SQL__ = "SELECT Titel, Laenge * 0.016667 AS Stunden, â€˜std.â€˜ AS inStunden FROM Film"
conn = sqlite3.connect("filme/filme.db")
cur = conn.cursor()
cur.execute(__SQL__)
rows = cur.fetchall()

for row in rows:
    for col in row:
        print(col,end=' ')
    print()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOperationalError[0m                          Traceback (most recent call last)
Input [0;32mIn [8][0m, in [0;36m<cell line: 6>[0;34m()[0m
[1;32m      4[0m conn [38;5;241m=[39m sqlite3[38;5;241m.[39mconnect([38;5;124m"[39m[38;5;124mfilme/filme.db[39m[38;5;124m"[39m)
[1;32m      5[0m cur [38;5;241m=[39m conn[38;5;241m.[39mcursor()
[0;32m----> 6[0m [43mcur[49m[38;5;241;43m.[39;49m[43mexecute[49m[43m([49m[43m__SQL__[49m[43m)[49m
[1;32m      7[0m rows [38;5;241m=[39m cur[38;5;241m.[39mfetchall()
[1;32m      9[0m [38;5;28;01mfor[39;00m row [38;5;129;01min[39;00m rows:

[0;31mOperationalError[0m: no such column: â€˜std.â€˜
OperationalError: no such column: â€˜std.â€˜

